version: '3.4'

services:
  greeting-api:
    container_name: greeting-api
    ports:
      - 5001:80
    image: ${DOCKER_REGISTRY-}greeting-api
    build:
      context: .\GreetingApi
      dockerfile: Dockerfile

  greeting-web:
    container_name: greeting-web
    ports:
      - 5000:80
    image: ${DOCKER_REGISTRY-}greeting-web
    environment:
        - "ApiConfiguration__ApiUrlGreeting=http://greeting-api:80"
    build:
      context: .\GreetingClient
      dockerfile: Dockerfile

    depends_on:
      - greeting-api

