apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: greeting-web
  name: greeting-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: greeting-web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -c
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: greeting-web
    spec:
      containers:
      - env:
        - name: ApiConfiguration__ApiUrlGreeting
          value: http://greeting-api:80
        image: localregistry:5000/demo/images/greeting-web
        imagePullPolicy: IfNotPresent
        name: greeting-web
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
